name: on-push-test
run-name: Test on push to test.

on: [push]
jobs:
  local-example:
    uses: ./.github/workflows/local-example.yml
    if: ${{ github.ref != 'refs/heads/main' }}
  cloud-example:
    uses: ./.github/workflows/cloud-example.yml
    if: ${{ github.ref == 'refs/heads/main' }}
    with:
      registry-name: ghcr.io
      image-name: octoml/octo-cli-workflows/yolov5s-skylake-accelerated
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      octoml-access-token: ${{ secrets.OCTOML_ACCESS_TOKEN }}