name: on-push-test
run-name: Test on push to test.
on: [push]
jobs:
  build-and-deploy-and-infer:
    runs-on: ubuntu-latest
    steps:
      - name: cloud-example
        uses: ./.github/workflows/cloud-example.yml