name: on-push-test
run-name: Test on push to test.

on:
  push:
    branches:
      - main
jobs:
  cloud-example:
    uses: ./.github/workflows/cloud-example.yml
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      octoml-access-token: ${{ secrets.OCTOML_ACCESS_TOKEN }}

on:
  push:
    branches-ignore:
      - main
jobs:
  local-example:
    uses: ./.github/workflows/local-example.yml