name: on-push-test
run-name: Test on push to test.
on: [push]
jobs:
  build-and-deploy-and-infer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Pull LFS
        run: git lfs pull
      # - name: Setup upterm session
      #  uses: lhotari/action-upterm@v1
      - name: Run deployment and inference
        env:
          OCTOML_AGREE_TO_TERMS: 1
          OCTOML_TELEMETRY: false
        run: |
          octoml package | octoml build | octoml deploy
      - name: Inference
        run: |
          apt-get update
          apt-get upgrade -y
          DEBIAN_FRONTEND=noninteractive apt-get install -y python3.8 python3-pip libgl1-mesa-glx libglib2.0-0
          pip3 install -r ./yolov5/requirements.txt
          pip3 install tritonclient[all]
          python3.8 ./yolov5/detect.py --weights http://localhost:8000 --source cat.jpg
      - name: Archive inference results
        uses: actions/upload-artifact@v3
        with:
          name: inference-result
          path: yolov5/runs/detect/exp
