name: on-push-test
run-name: Test on push to test.
on: [push]
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run deployment and inference
        uses: ./
