name: on-push-test
run-name: Test on push to test.

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: octoml/octo-cli-workflows/yolov5s-skylake-accelerated

on: [push]
jobs:
  local-example:
    uses: ./.github/workflows/local-example.yml
    if: ${{ github.ref != 'refs/heads/main' }}
  cloud-example:
    uses: ./.github/workflows/cloud-example.yml
    if: ${{ github.ref == 'refs/heads/main' }}
    with:
      registry-name: ${{ env.REGISTRY }}
      image-name: ${{ env.IMAGE_NAME }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      octoml-access-token: ${{ secrets.OCTOML_ACCESS_TOKEN }}